# -*- Mode:sh -*-
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
# Proxy settings in China
HTTP_PROXY="http://127.0.0.1:8118"
HTTPS_PROXY="http://127.0.0.1:8118"
export HTTP_PROXY
export HTTPS_PROXY
# Use GUI emacs with Chinese IME in Toolboxes
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
NVIM=$(which nvim 2>/dev/null)
EDITOR=${NVIM:=/usr/bin/vi}
export EDITOR
TERM=xterm-256color
export TERM
# User specific aliases and functions
alias e='emacsclient'
